# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ipv6start', models.CharField(max_length=100)),
                ('ipv6end', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('ipv6start',),
            },
        ),
    ]
